### ISSUE TITLE
Syntax errors should result in exceptions rather than being logged to System.err and otherwise ignored

### ISSUE THREAD

**Issue by garethdanielsmith-connect** [connect-group/thymesheet#10]
The error messages that are logged are easy to miss, and also don't include the path to the broken file.

It seems you can make exceptions be thrown by inserting this code at line `135` in `ThymesheetPreprocessor.java`

`parser.setErrorHandler(ThrowCssExceptionErrorHandler.INSTANCE);`

I can send a pull request with a test if you like.

**Comment by 4dz** [comment]
This patch has been submitted to the nexus maven repo for publishing as v2.1.3 - should be available later today.

**Comment by garethdanielsmith-connect** [comment]
Thanks @4dz 👍 

Any chance of a `thymesheet-spring3/4` release as well (that uses the new version of `thymesheet`)?
